### ISSUE TITLE
大佬,根本用不了,我看json里需要引入图片,你也没提供图片怎么用?

### ISSUE THREAD

**Issue by JiangJiYue** [ErSuan/gotoscan#3]
大佬,根本用不了,我看json里需要引入图片,你也没提供图片怎么用?

**Comment by newbe3three** [comment]
不需要图片呀。代码中的逻辑是根据json文件请求图片，如果请求成功则会对比其md5值是否和json文件中存放的一致。
也就是说是根据图片的md5值进行判断的，因此在json文件中存放的是对应的md5值。json文件在cmd目录下。

**Comment by JiangJiYue** [comment]
抱歉,不加协议头https/http识别不出来

**Comment by newbe3three** [comment]
确实是，写代码也没考虑这些≧ ﹏ ≦，后续再优化。<(￣︶￣)↗[GO!]

**Comment by JiangJiYue** [comment]
哈哈哈,协议头有时候确实不在意
